config/routes.rb
Rails.application.routes.draw do
  get 'galleries' => 'galleries#index'

  get 'contacts' => 'contacts#index'

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/index.html.erb
<% @title="Versatile Contracting Group | Contact" %>

app/views/galleries/index.html.erb
<% @title="Versatile Contracting Group | Gallery" %>
<h1>Galleries#index</h1>
<p>Find me in app/views/galleries/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"d>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container-head row">
        <div id="branding">
          <h1><%= link_to "VCG", root_path, { style:'margin: 0; font-size: 40px;' } %></h1>
        </div>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Gallery", galleries_path %></li>
            <li><%= link_to "Contact", contacts_path %></li>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>Copyright © 2018 Versatile Contracting Group</p>
    </footer>
  </body>
</html>

app/views/welcome/about.html.erb
<% @title="Versatile Contracting Group | About" %>
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<% @title="Versatile Contracting Group | Home" %>
<section id="showcase">
  <div class="container-showcase">
    <h1>Versatile Contracting Group</h1>
    <p>Atlanta based landscaping and hardscaping</p>
  </div>
</section>
<section id="boxes">
  <div class="container-boxes row">
    <div class="box">
      <%= image_tag("bricks.png", :alt => "stones pic") %>
      <h2>Stone, Vaneer, Concrete and Paver</h2>
      <p>We transform patios, walkways, driveways, walls, columns, subdivision monument signs, and more!</p>
    </div>
    <div class="box">
      <%= image_tag("firepit_illustration.png", :alt => "stones pic") %>
      <h2>Outdoor Firepits and Kitchens</h2>
      <p>Take your backyard to the next level with a kitchen or firepit.</p>
    </div>
    <div class="box">
      <%= image_tag("pipe.png", :alt => "stones pic") %>
      <h2>Grading and Drainage Services</h2>
      <p>We take care of all grading and drainage work, while making your space look incredible.</p>
    </div>
  </div>
  <!-- Add picture slideshow -->
</section>
<div class="clear"></div>
<div class="gallery-link">
  <div class="row">
    <div id="gallery-description">
      <h2>Check out more pictures of our past projects:</h2>
    </div>
    <div id="gallery-button">
      <%= button_to "Gallery", galleries_path, method: :get, :class => "gallery-button" %>
    </div>
    <div class="clear"></div>
  </div>
</div>
<section class="wrap row" scroll="no">
  <div id="arrow-left" class="fa fa-angle-left arrow"></div>
  <div id="slider">
    <div class="slide slide1">
      <div class="slide-content">
      </div>
    </div>
    <div class="slide slide2">
      <div class="slide-content">
        <span></span>
      </div>
    </div>
    <div class="slide slide3">
      <div class="slide-content">
        <span></span>
      </div>
    </div>
  </div>
  <div id="arrow-right" class="fa fa-angle-right arrow"></div>
</section>